approvedGitRepositories:
  - "https://github.com/getappmap/*"

enableGlobalCache: true

enableScripts: true

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org'

yarnPath: .yarn/releases/yarn-4.18.0.cjs

packageExtensions:
  '@vue/cli-plugin-unit-jest@4.5.15':
    peerDependencies:
      vue: '^2'
      vue-template-compiler: '^2'
  'rollup-plugin-sass@1.2.10':
    peerDependencies:
      rollup: '^1.20.0||^2.0.0'
  'rollup-plugin-vue@5.1.9':
    peerDependencies:
      postcss: '>=6.0'
  'swagger-parser@10.0.3':
    peerDependencies:
      openapi-types: '>=7'
  'openapi-diff@0.23.6':
    peerDependencies:
      openapi-types: '>=7'
