/* eslint-disable global-require, @typescript-eslint/no-var-requires */
// require() returns any; the loaders hand that to lazyCommand, which reads the module's shape.
/* eslint-disable @typescript-eslint/no-unsafe-return */
import type { LazyCommandSpec } from './lib/lazyCommand';

// The subcommands of the `appmap` CLI. Each entry gives yargs the command's
// name, description and aliases, and a loader for the module that implements
// it; the module is loaded only when that command runs (see lazyCommand).
//
// `command`, `describe` and `aliases` must match the module's own values.
// tests/unit/cliCommands.spec.ts loads every module and checks that.
const commands: LazyCommandSpec[] = [
  {
    command: 'index',
    describe: 'Compute fingerprints and update index files for all appmaps in a directory',
    load: () => require('./cmds/index/index'),
  },
  {
    command: 'openapi',
    describe: 'Generate OpenAPI from AppMaps in a directory',
    aliases: ['swagger'],
    load: () => require('./cmds/openapi/openapi'),
  },
  {
    command: 'install [directory]',
    describe: 'Install and configure an AppMap language agent',
    aliases: ['i', 'install-agent'],
    load: () => require('./cmds/agentInstaller/install-agent'),
  },
  {
    command: 'open [appmap-file]',
    describe: 'Open an AppMap in the system default browser',
    load: () => require('./cmds/open/open'),
  },
  {
    command: 'record [mode]',
    describe: 'Create an AppMap via interactive recording, aka remote recording.',
    load: () => require('./cmds/record/record'),
  },
  {
    command: 'status [directory]',
    describe: 'Check the status of the current project for the AppMap language agent',
    aliases: ['s'],
    load: () => require('./cmds/agentInstaller/status'),
  },
  {
    command: 'stats [directory]',
    describe: 'Show statistics about events from an AppMap or from all AppMaps in a directory',
    load: () => require('./cmds/stats/stats'),
  },
  {
    command: 'inspect <code-object>',
    describe:
      'Search AppMaps for references to a code object (package, function, class, query, route, etc) and print available event info',
    load: () => require('./cmds/inspect/inspect'),
  },
  {
    command: 'sequence-diagram <appmap...>',
    describe: 'Generate a sequence diagram for an AppMap',
    load: () => require('./cmds/sequenceDiagram'),
  },
  {
    command: 'sequence-diagram-diff base-diagram head-diagram',
    describe: 'Diff sequence diagrams that are represented as JSON',
    load: () => require('./cmds/sequenceDiagramDiff'),
  },
  {
    command: 'prune <file>',
    describe: 'Make an appmap file smaller by removing events',
    load: () => require('./cmds/prune/prune'),
  },
  {
    command: 'trim <files..>',
    describe:
      'Shrink AppMaps by truncating captured parameter, return, receiver, and message values',
    load: () => require('./cmds/trim/trim'),
  },
  {
    command: 'sanitize <files..>',
    describe:
      'Replace captured values in AppMaps with per-file equality-preserving tokens, so the files cannot carry secrets',
    load: () => require('./cmds/sanitize/sanitize'),
  },
  {
    command: 'archive',
    describe: 'Build an AppMap archive from a directory containing AppMaps',
    load: () => require('./cmds/archive/archive'),
  },
  {
    command: 'restore',
    describe: 'Restore the most current available AppMap data from available archives',
    load: () => require('./cmds/archive/restore'),
  },
  {
    command: 'compare',
    describe: 'Compare runtime code behavior between base and head revisions',
    load: () => require('./cmds/compare/compare'),
  },
  {
    command: 'compare-report <report-directory>',
    describe: 'Generate a report document from comparison data generated by the compare command.',
    load: () => require('./cmds/compare-report/compareReport'),
  },
  {
    command: 'inventory [output-file]',
    describe: 'Generate a JSON report describing the contents of a repository.',
    load: () => require('./cmds/inventory/inventory'),
  },
  {
    command: 'inventory-report <report-json-file> [output-file]',
    describe: 'Generate a report document describing the current state of a repository.',
    load: () => require('./cmds/inventory-report/inventoryReport'),
  },
  {
    command: 'search <query>',
    describe: 'Search AppMaps, or a single AppMap, for search matches to a full-text query.',
    load: () => require('./cmds/search/search'),
  },
  {
    command: 'rpc',
    describe: 'Run AppMap JSON-RPC server',
    load: () => require('./cmds/index/rpc'),
  },
  {
    command: 'rpc-client <function> [request]',
    describe: 'Invoke an RPC function without running the server',
    load: () => require('./cmds/rpcClient'),
  },
  {
    command: 'navie [question..]',
    describe: 'Explain a question using Navie',
    load: () => require('./cmds/navie'),
  },
  {
    command: 'apply [filename]',
    describe: 'Apply file changes using search and replace strings or an XML changeset file',
    load: () => require('./cmds/apply'),
  },
  {
    command: 'query',
    describe:
      'Query AppMap recordings (endpoints, find, tree, related, hotspots, compare, mcp, ui)',
    load: () => require('./cmds/query/query'),
  },
  {
    command: 'run-test <filename...>',
    describe:
      'Runs a test according to the configuration available in the environment and .appmaprc.yml',
    load: () => require('./cmds/runTest'),
  },
  {
    command: 'test-telemetry',
    describe: false,
    load: () => require('./cmds/testTelemetry'),
  },
];

export default commands;
