scanners:
  - id: http500
  - id: missingContentType
  - id: missingAuthentication
    properties:
      routes: [ /\/api\// ]
  - id: nPlusOneQuery
  - id: queryFromView
    include:
      - /microposts/.test(event.sqlQuery)
      - >
        const root = event.ancestors().pop();
        root && root.route && root.requestMethod === 'POST';
  - id: saveWithoutValidation
  - id: secretInLog
  - id: slowHttpServerRequest
  - id: slowQuery
  - id: tooManyUpdates
    properties:
      maxUpdates: 2
  - id: authzBeforeAuthn