import yargs from 'yargs';
import lazyHandler from '../../lib/lazyHandler';

export const command = 'inventory-report <report-json-file> [output-file]';
export const describe = 'Generate a report document describing the current state of a repository.';

export const builder = (args: yargs.Argv) => {
  args.positional('report-json-file', {
    type: 'string',
    describe: `JSON report file to read. This file is generated by the 'inventory' command.`,
    demandOption: true,
  });

  args.positional('output-file', {
    type: 'string',
    describe: `Markdown output file. If not specified, the report is written to stdout.`,
    demandOption: true,
  });

  args.option('directory', {
    describe: 'program working directory',
    type: 'string',
    alias: 'd',
  });

  args.option('template-name', {
    type: 'string',
    describe: `Template name.`,
    default: 'welcome',
    choices: ['welcome', 'summary'],
    alias: 't',
  });

  args.option('source-url', {
    describe: `Base URL to link to a source file. The relative path to the source file will be added to the URL path.`,
    type: 'string',
  });

  args.option('appmap-url', {
    describe: `Base URL to link to AppMaps. A 'path' parameter will be added with the relative path from the report directory to the AppMap JSON file.`,
    type: 'string',
  });

  return args.strict();
};

export const handler = lazyHandler(() => import('./inventoryReportHandler'));
